development:
  adapter: tinytds
  encoding: utf8
  database: ydh14
  pool: 16
  username: scl
  password: scl@54325166
  host: 116.228.3.80
  port: 11433

test:
  adapter: tinytds
  encoding: utf8
  database: ydh14
  pool: 16
  username: scl
  password: scl@54325166
  host: 116.228.3.80
  port: 11433

production:
  adapter: tinytds
  encoding: utf8
  database: ydh14
  pool: 16
  username: scl
  password: scl@54325166
  host: 116.228.3.80
  port: 11433