default: &default
  powered: jeffrey
  email: jeffrey6052@163.com
  redis:
    online: false
    expire: 86400

development:
  <<: *default
  static_root: '/assets'
  static_version: ''
  oss_root: ''

production:
  <<: *default
  static_root: '/assets'
  static_version: ''
  oss_root: ''